name: Backend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  backend-test:

    name: Backend Test

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"


    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run pytest
      run: |
        cd backend

        pytest tests 
        -v 
        --cov=app 
        --cov-report=term 
        --cov-fail-under=80

